#!/bin/bash

getDate(){
	date

	return 

}

getDate

name="BO"

localFun(){
	local name="Paul"
	echo $name
	return
}

localFun
echo $name

getSum(){
	local num1=$1
	local num2=$2

	local sum=$((num1+num2))
	echo $sum
}

num1=3
num3=7
sum=$(getSum num1 num4)
echo $sum
